workflows:
  ios-release-build:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      vars:
        CAPACITOR_CONFIG_PATH: "capacitor.config.ts"
      node: 18.16.0
    scripts:
      - name: Install Dependencies
        script: |
          npm ci   # clean install for reproducibility
      - name: Add iOS Platform
        script: |
          npm install @capacitor/ios
          npx cap add ios
          npx cap sync
      - name: Build Angular App
        script: |
          npm run build     # runs ng build --configuration production from package.json
      - name: Copy Web Assets
        script: |
          npx cap copy
      - name: Build iOS with Xcode
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release
    artifacts:
      - ios/build/**/Build/Products/Release-iphoneos/*.app
      - ios/build/**/Build/Products/Release-iphoneos/*.ipa
